server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**,/api/accounts/**,/api/transactions/**,/api/loans/**,/api/dashboard/**
          filters:
            - StripPrefix=0
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin123@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: my-very-secret-jwt-key-for-nexusbank-2024-secure-application

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
